export type StorageProvider = 'local' | 's3' | 'cloudinary';

export enum FilePurpose {
  PROFILE_PHOTO = 'PROFILE_PHOTO',
  ORIGINALITY_STATEMENT = 'ORIGINALITY_STATEMENT',
  COMPETITION_WORK = 'COMPETITION_WORK',
  PAYMENT_PROOF = 'PAYMENT_PROOF',
  DEATH_CERTIFICATE = 'DEATH_CERTIFICATE',
  OTHER = 'OTHER',
  GENERAL = 'GENERAL',
}
