export enum AuditCategory {
  AUTH = 'AUTH',
  SECURITY = 'SECURITY',
  INVENTORY = 'INVENTORY',
  EMPLOYEE = 'EMPLOYEE',
  ORDER = 'ORDER',
  PRODUCT = 'PRODUCT',
  FINANCE = 'FINANCE',
  SYSTEM = 'SYSTEM',
  // ── WarisTech Domain ──
  WARIS_ASSET = 'WARIS_ASSET',
  WARIS_FAMILY = 'WARIS_FAMILY',
  WARIS_CALCULATION = 'WARIS_CALCULATION',
}

export enum AuditSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum AuditStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}

export enum AuditAction {
  // ── Authentication & Security ──
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_VERIFY_EMAIL = 'AUTH_VERIFY_EMAIL',
  AUTH_PASSWORD_RESET_REQUEST = 'AUTH_PASSWORD_RESET_REQUEST',
  AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS',
  AUTH_PASSWORD_CHANGE = 'AUTH_PASSWORD_CHANGE',
  AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH',
  AUTH_ACCESS_DENIED = 'AUTH_ACCESS_DENIED',

  // ── User & Employee Management (Internal) ──
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_STATUS_CHANGE = 'USER_STATUS_CHANGE',
  USER_ROLE_CHANGE = 'USER_ROLE_CHANGE',
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_RESIGN = 'EMPLOYEE_RESIGN',

  // ── Inventory & Warehouse (Internal) ──
  INVENTORY_STOCK_IN = 'INVENTORY_STOCK_IN',
  INVENTORY_STOCK_OUT = 'INVENTORY_STOCK_OUT',
  INVENTORY_STOCK_ADJUST = 'INVENTORY_STOCK_ADJUST',
  INVENTORY_OPNAME = 'INVENTORY_OPNAME',
  WAREHOUSE_TRANSFER = 'WAREHOUSE_TRANSFER',

  // ── Product & Catalog ──
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  BRAND_CREATE = 'BRAND_CREATE',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_PRICE_CHANGE = 'PRODUCT_PRICE_CHANGE',

  // ── Order & Transaction (Public E-Commerce) ──
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',

  // ── Media & File Storage ──
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',

  // ── WarisTech: Harta (Assets) ──
  ASSET_CREATED = 'ASSET_CREATED',
  ASSET_UPDATED = 'ASSET_UPDATED',
  ASSET_DELETED = 'ASSET_DELETED',
  ASSET_VERIFIED = 'ASSET_VERIFIED',
  ASSET_REJECTED = 'ASSET_REJECTED',
  ASSET_FORCE_CLOSED = 'ASSET_FORCE_CLOSED',
  NOTARIS_SHARE_ESCROWED = 'NOTARIS_SHARE_ESCROWED',
  VAULT_SHARE_RELEASED = 'VAULT_SHARE_RELEASED',
  KEY_SHARES_ROTATED = 'KEY_SHARES_ROTATED',
  KEY_ROTATION_REMINDER_SENT = 'KEY_ROTATION_REMINDER_SENT',
  LEGAL_FALLBACK_REQUESTED = 'LEGAL_FALLBACK_REQUESTED',

  // ── WarisTech: Tinjauan Manual Bukti Pencairan (menggantikan AI forensik) ──
  LIQUIDATION_PROOF_UPLOADED = 'LIQUIDATION_PROOF_UPLOADED',
  LIQUIDATION_PROOF_APPROVED = 'LIQUIDATION_PROOF_APPROVED',
  LIQUIDATION_PROOF_REJECTED = 'LIQUIDATION_PROOF_REJECTED',

  // ── WarisTech: Keluarga (Family Members) ──
  FAMILY_MEMBER_INVITED = 'FAMILY_MEMBER_INVITED',
  FAMILY_MEMBER_CONFIRMED = 'FAMILY_MEMBER_CONFIRMED',
  FAMILY_MEMBER_VERIFIED = 'FAMILY_MEMBER_VERIFIED',
  FAMILY_MEMBER_REJECTED = 'FAMILY_MEMBER_REJECTED',

  // ── WarisTech: Verifikasi Berjenjang (Witness & Death Verification) ──
  INHERITANCE_VERIFICATION_GATE_BLOCKED = 'INHERITANCE_VERIFICATION_GATE_BLOCKED',
  INHERITANCE_VERIFICATION_APPROVED = 'INHERITANCE_VERIFICATION_APPROVED',
  ASSET_COOLDOWN_STARTED = 'ASSET_COOLDOWN_STARTED',
  ASSET_COOLDOWN_EXPIRED = 'ASSET_COOLDOWN_EXPIRED',

  // ── WarisTech: Proof-of-Life Bertahap ──
  PROOF_OF_LIFE_FORMAL_VERIFICATION_TRIGGERED = 'PROOF_OF_LIFE_FORMAL_VERIFICATION_TRIGGERED',

  // ── WarisTech: Preferensi Skema Hukum Waris ──
  ASSET_ALLOCATION_OVERRIDDEN = 'ASSET_ALLOCATION_OVERRIDDEN',

  // ── UU PDP: Persetujuan & Insiden Pelindungan Data ──
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  DATA_BREACH_REPORTED = 'DATA_BREACH_REPORTED',

  // ── WarisTech: Perhitungan Waris (Calculation) ──
  WARIS_CALCULATION_SIMULATED = 'WARIS_CALCULATION_SIMULATED',
}
