export enum AuditCategory {
  AUTH = 'AUTH',
  SECURITY = 'SECURITY',
  INVENTORY = 'INVENTORY',
  EMPLOYEE = 'EMPLOYEE',
  ORDER = 'ORDER',
  PRODUCT = 'PRODUCT',
  FINANCE = 'FINANCE',
  SYSTEM = 'SYSTEM',
}

export enum AuditSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum AuditStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}

export enum AuditAction {
  // ── Authentication & Security ──
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_VERIFY_EMAIL = 'AUTH_VERIFY_EMAIL',
  AUTH_PASSWORD_RESET_REQUEST = 'AUTH_PASSWORD_RESET_REQUEST',
  AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS',
  AUTH_PASSWORD_CHANGE = 'AUTH_PASSWORD_CHANGE',
  AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH',
  AUTH_ACCESS_DENIED = 'AUTH_ACCESS_DENIED',

  // ── User & Employee Management (Internal) ──
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_STATUS_CHANGE = 'USER_STATUS_CHANGE',
  USER_ROLE_CHANGE = 'USER_ROLE_CHANGE',
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_RESIGN = 'EMPLOYEE_RESIGN',

  // ── Inventory & Warehouse (Internal) ──
  INVENTORY_STOCK_IN = 'INVENTORY_STOCK_IN',
  INVENTORY_STOCK_OUT = 'INVENTORY_STOCK_OUT',
  INVENTORY_STOCK_ADJUST = 'INVENTORY_STOCK_ADJUST',
  INVENTORY_OPNAME = 'INVENTORY_OPNAME',
  WAREHOUSE_TRANSFER = 'WAREHOUSE_TRANSFER',

  // ── Product & Catalog ──
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  BRAND_CREATE = 'BRAND_CREATE',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_PRICE_CHANGE = 'PRODUCT_PRICE_CHANGE',

  // ── Order & Transaction (Public E-Commerce) ──
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',

  // ── Media & File Storage ──
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
}
